// Auto-generated by scripts/import-certificates.mjs + scripts/certificates-to-pdf.mjs — do not hand-edit.
export interface CertificateFile {
  title: string;
  category: string;
  categorySlug: string;
  fileName: string;
  type: "pdf" | "image";
  url: string;
}

export const certificateFiles: CertificateFile[] = [
  {
    "title": "Critical Thinking & Problem Solving",
    "category": "ADGM Academy",
    "categorySlug": "adgm-academy",
    "fileName": "Critical Thinking & Problem Solving.pdf",
    "type": "pdf",
    "url": "/certificates/adgm-academy/Critical%20Thinking%20&%20Problem%20Solving.pdf"
  },
  {
    "title": "ADGM Data Protection",
    "category": "ADNOC",
    "categorySlug": "adnoc",
    "fileName": "ADGM Data Protection.pdf",
    "type": "pdf",
    "url": "/certificates/adnoc/ADGM%20Data%20Protection.pdf"
  },
  {
    "title": "Anti-Bribery Training",
    "category": "ADNOC",
    "categorySlug": "adnoc",
    "fileName": "Anti-Bribery Training.pdf",
    "type": "pdf",
    "url": "/certificates/adnoc/Anti-Bribery%20Training.pdf"
  },
  {
    "title": "Anti-Money Laundering and Counter-Terrorist Financing",
    "category": "ADNOC",
    "categorySlug": "adnoc",
    "fileName": "Anti-Money Laundering and Counter-Terrorist Financing.pdf",
    "type": "pdf",
    "url": "/certificates/adnoc/Anti-Money%20Laundering%20and%20Counter-Terrorist%20Financing.pdf"
  },
  {
    "title": "Gifts & Entertainment",
    "category": "ADNOC",
    "categorySlug": "adnoc",
    "fileName": "Gifts & Entertainment.pdf",
    "type": "pdf",
    "url": "/certificates/adnoc/Gifts%20&%20Entertainment.pdf"
  },
  {
    "title": "Advance Google Data Analytics",
    "category": "Coursera",
    "categorySlug": "coursera",
    "fileName": "Advance Google Data Analytics.pdf",
    "type": "pdf",
    "url": "/certificates/coursera/Advance%20Google%20Data%20Analytics.pdf"
  },
  {
    "title": "BigQuery for Data Analysts",
    "category": "Coursera",
    "categorySlug": "coursera",
    "fileName": "BigQuery for Data Analysts.pdf",
    "type": "pdf",
    "url": "/certificates/coursera/BigQuery%20for%20Data%20Analysts.pdf"
  },
  {
    "title": "Databases and SQL for Data Science with Python",
    "category": "Coursera",
    "categorySlug": "coursera",
    "fileName": "Databases and SQL for Data Science with Python.pdf",
    "type": "pdf",
    "url": "/certificates/coursera/Databases%20and%20SQL%20for%20Data%20Science%20with%20Python.pdf"
  },
  {
    "title": "Getting Started with Power BI Desktop",
    "category": "Coursera",
    "categorySlug": "coursera",
    "fileName": "Getting Started with Power BI Desktop.pdf",
    "type": "pdf",
    "url": "/certificates/coursera/Getting%20Started%20with%20Power%20BI%20Desktop.pdf"
  },
  {
    "title": "Google Data Analytics",
    "category": "Coursera",
    "categorySlug": "coursera",
    "fileName": "Google Data Analytics.pdf",
    "type": "pdf",
    "url": "/certificates/coursera/Google%20Data%20Analytics.pdf"
  },
  {
    "title": "IBM Data Science",
    "category": "Coursera",
    "categorySlug": "coursera",
    "fileName": "IBM Data Science.pdf",
    "type": "pdf",
    "url": "/certificates/coursera/IBM%20Data%20Science.pdf"
  },
  {
    "title": "Microsoft Power BI Data Analyst",
    "category": "Coursera",
    "categorySlug": "coursera",
    "fileName": "Microsoft Power BI Data Analyst.pdf",
    "type": "pdf",
    "url": "/certificates/coursera/Microsoft%20Power%20BI%20Data%20Analyst.pdf"
  },
  {
    "title": "Salesforce Sales Development Representative",
    "category": "Coursera",
    "categorySlug": "coursera",
    "fileName": "Salesforce Sales Development Representative.pdf",
    "type": "pdf",
    "url": "/certificates/coursera/Salesforce%20Sales%20Development%20Representative.pdf"
  },
  {
    "title": "McKinsey Forward Program Badge20240815-8-8bdjc8",
    "category": "McKinsey Forward Program",
    "categorySlug": "mckinsey-forward-program",
    "fileName": "McKinsey_Forward_Program_Badge20240815-8-8bdjc8.pdf",
    "type": "pdf",
    "url": "/certificates/mckinsey-forward-program/McKinsey_Forward_Program_Badge20240815-8-8bdjc8.pdf"
  },
  {
    "title": "oracle data visulasation challenge",
    "category": "Oracle",
    "categorySlug": "oracle",
    "fileName": "oracle_data_visulasation_challenge.pdf",
    "type": "pdf",
    "url": "/certificates/oracle/oracle_data_visulasation_challenge.pdf"
  },
  {
    "title": "Tricentis qTest Fundamentals − qTest Project creation & qTest Explorer",
    "category": "Tricentis Academy",
    "categorySlug": "tricentis-academy",
    "fileName": "Tricentis qTest Fundamentals − qTest Project creation & qTest Explorer.pdf",
    "type": "pdf",
    "url": "/certificates/tricentis-academy/Tricentis%20qTest%20Fundamentals%20%E2%88%92%20qTest%20Project%20creation%20&%20qTest%20Explorer.pdf"
  },
  {
    "title": "Paginated Report - Power Bi Report Builder",
    "category": "Udemy",
    "categorySlug": "udemy",
    "fileName": "Paginated Report - Power Bi Report Builder.pdf",
    "type": "pdf",
    "url": "/certificates/udemy/Paginated%20Report%20-%20Power%20Bi%20Report%20Builder.pdf"
  },
  {
    "title": "SQL - MySQL for Data Analytics and Business Intelligence",
    "category": "Udemy",
    "categorySlug": "udemy",
    "fileName": "SQL - MySQL for Data Analytics and Business Intelligence.pdf",
    "type": "pdf",
    "url": "/certificates/udemy/SQL%20-%20MySQL%20for%20Data%20Analytics%20and%20Business%20Intelligence.pdf"
  },
  {
    "title": "Certificate of Appreciation",
    "category": "University",
    "categorySlug": "university",
    "fileName": "Certificate of Appreciation.pdf",
    "type": "pdf",
    "url": "/certificates/university/Certificate%20of%20Appreciation.pdf"
  },
  {
    "title": "Graduation Certificate",
    "category": "University",
    "categorySlug": "university",
    "fileName": "Graduation Certificate.pdf",
    "type": "pdf",
    "url": "/certificates/university/Graduation%20Certificate.pdf"
  },
  {
    "title": "1st place in the essay competition “MY HOME “ARTEK””",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "1st place in the essay competition “MY HOME “ARTEK””.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/1st%20place%20in%20the%20essay%20competition%20%E2%80%9CMY%20HOME%20%E2%80%9CARTEK%E2%80%9D%E2%80%9D.pdf"
  },
  {
    "title": "2023 Russian House, Damascus Active Participation Certificate",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "2023 Russian House, Damascus Active Participation Certificate.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/2023%20Russian%20House,%20Damascus%20Active%20Participation%20Certificate.pdf"
  },
  {
    "title": "2nd place in the International essay competition “MY BEST DAY IN ARTEK”",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "2nd place in the International essay competition “MY BEST DAY IN ARTEK”.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/2nd%20place%20in%20the%20International%20essay%20competition%20%E2%80%9CMY%20BEST%20DAY%20IN%20ARTEK%E2%80%9D.pdf"
  },
  {
    "title": "Accelerator of Social Projects",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Accelerator of Social Projects.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Accelerator%20of%20Social%20Projects.pdf"
  },
  {
    "title": "Active participation in events and volunteer movement in the Russian House in Syria",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Active participation in events and volunteer movement in the Russian House in Syria..pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Active%20participation%20in%20events%20and%20volunteer%20movement%20in%20the%20Russian%20House%20in%20Syria..pdf"
  },
  {
    "title": "Active participation in the public life of the Russian House",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Active participation in the public life of the Russian House.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Active%20participation%20in%20the%20public%20life%20of%20the%20Russian%20House.pdf"
  },
  {
    "title": "Artek",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Artek.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Artek.pdf"
  },
  {
    "title": "Artek 1st place in the sports and entertainment game  Fun Sportland",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Artek 1st place in the sports and entertainment game _Fun Sportland_.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Artek%201st%20place%20in%20the%20sports%20and%20entertainment%20game%20_Fun%20Sportland_.pdf"
  },
  {
    "title": "Artek(1)",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Artek(1).pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Artek(1).pdf"
  },
  {
    "title": "Artek(2)",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Artek(2).pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Artek(2).pdf"
  },
  {
    "title": "Cyber Security Incident Management",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Cyber Security Incident Management.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Cyber%20Security%20Incident%20Management.pdf"
  },
  {
    "title": "Day of National Unity",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Day of National Unity.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Day%20of%20National%20Unity.pdf"
  },
  {
    "title": "Day of National Unity(1)",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Day of National Unity(1).pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Day%20of%20National%20Unity(1).pdf"
  },
  {
    "title": "Graphic Design lecturer",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Graphic Design lecturer.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Graphic%20Design%20lecturer.pdf"
  },
  {
    "title": "History",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "History.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/History.pdf"
  },
  {
    "title": "International Youth Forum  The Future of the Russian World",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "International Youth Forum  The Future of the Russian World.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/International%20Youth%20Forum%20%20The%20Future%20of%20the%20Russian%20World.pdf"
  },
  {
    "title": "Media Expo Syria",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Media Expo Syria.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Media%20Expo%20Syria.pdf"
  },
  {
    "title": "Mother Language Day",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Mother Language Day.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Mother%20Language%20Day.pdf"
  },
  {
    "title": "New Year flashmob, photo contest",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "New Year flashmob, photo contest..pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/New%20Year%20flashmob,%20photo%20contest..pdf"
  },
  {
    "title": "Rasul Gamzatov",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Rasul Gamzatov.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Rasul%20Gamzatov.pdf"
  },
  {
    "title": "RUS Dance",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "RUS Dance.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/RUS%20Dance.pdf"
  },
  {
    "title": "Russia. Historical Heritage",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Russia. Historical Heritage.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Russia.%20Historical%20Heritage.pdf"
  },
  {
    "title": "Russian Compatriots Living Abroad",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Russian Compatriots Living Abroad.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Russian%20Compatriots%20Living%20Abroad.pdf"
  },
  {
    "title": "Russian Geographical Society",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Russian Geographical Society.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Russian%20Geographical%20Society.pdf"
  },
  {
    "title": "Russian House in Syria",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Russian House in Syria.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Russian%20House%20in%20Syria.pdf"
  },
  {
    "title": "Russian Post winner",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Russian Post winner.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Russian%20Post%20winner.pdf"
  },
  {
    "title": "Russian world without borders",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Russian world without borders.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Russian%20world%20without%20borders.pdf"
  },
  {
    "title": "School of Young Leaders",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "School of Young Leaders.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/School%20of%20Young%20Leaders.pdf"
  },
  {
    "title": "TED",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "TED.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/TED.pdf"
  },
  {
    "title": "The World Forum for Public Joy online",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "The World Forum for Public Joy online.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/The%20World%20Forum%20for%20Public%20Joy%20online.pdf"
  },
  {
    "title": "Thematic competitions",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Thematic competitions.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Thematic%20competitions.pdf"
  },
  {
    "title": "Youth Rally of Russian Compatriots",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Youth Rally of Russian Compatriots.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Youth%20Rally%20of%20Russian%20Compatriots.pdf"
  },
  {
    "title": "Zabava",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Zabava.pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Zabava.pdf"
  },
  {
    "title": "Zabava(1)",
    "category": "Volunteering",
    "categorySlug": "volunteering",
    "fileName": "Zabava(1).pdf",
    "type": "pdf",
    "url": "/certificates/volunteering/Zabava(1).pdf"
  }
];
