import { readFile, writeFile, unlink } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { PDFDocument } from "pdf-lib";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const manifestPath = path.join(root, "src", "content", "certificateFiles.generated.ts");
const publicDir = path.join(root, "public");

async function loadManifest() {
  const src = await readFile(manifestPath, "utf8");
  const match = src.match(/certificateFiles: CertificateFile\[\] = (\[[\s\S]*\]);/);
  if (!match) throw new Error("Could not locate certificateFiles array in manifest");
  return JSON.parse(match[1]);
}

function sniffImageKind(bytes) {
  if (bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47) {
    return "png";
  }
  if (bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) {
    return "jpg";
  }
  return null;
}

async function imageToPdf(absImagePath) {
  const bytes = await readFile(absImagePath);
  const kind = sniffImageKind(bytes) ?? (absImagePath.toLowerCase().endsWith(".png") ? "png" : "jpg");
  const pdfDoc = await PDFDocument.create();
  const image = kind === "png" ? await pdfDoc.embedPng(bytes) : await pdfDoc.embedJpg(bytes);
  const { width, height } = image;
  const page = pdfDoc.addPage([width, height]);
  page.drawImage(image, { x: 0, y: 0, width, height });
  return pdfDoc.save();
}

async function main() {
  const manifest = await loadManifest();
  let converted = 0;

  for (const entry of manifest) {
    if (entry.type === "pdf") continue;

    const urlPath = decodeURIComponent(entry.url);
    const absPath = path.join(publicDir, urlPath.replace(/^\//, ""));

    const pdfBytes = await imageToPdf(absPath);

    const newFileName = entry.fileName.replace(/\.[^.]+$/, "") + ".pdf";
    const newAbsPath = path.join(path.dirname(absPath), newFileName);
    await writeFile(newAbsPath, pdfBytes);
    await unlink(absPath);

    entry.fileName = newFileName;
    entry.type = "pdf";
    // Use encodeURI, not encodeURIComponent — see the note in
    // scripts/import-certificates.mjs for why.
    entry.url = `/certificates/${entry.categorySlug}/${encodeURI(newFileName)}`;

    converted++;
  }

  const body = `// Auto-generated by scripts/import-certificates.mjs + scripts/certificates-to-pdf.mjs — do not hand-edit.\nexport interface CertificateFile {\n  title: string;\n  category: string;\n  categorySlug: string;\n  fileName: string;\n  type: "pdf" | "image";\n  url: string;\n}\n\nexport const certificateFiles: CertificateFile[] = ${JSON.stringify(manifest, null, 2)};\n`;
  await writeFile(manifestPath, body);

  console.log(`Converted ${converted} image(s) to PDF. Manifest updated (${manifest.length} total entries).`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
